language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0

matrix:
  fast_finish: true

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("MultipleTesting"); Pkg.test("MultipleTesting"; coverage=true)'

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("MultipleTesting")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder(), flags="julia_$(VERSION.major)_$(VERSION.minor)")'
  - julia -e 'using Pkg; cd(Pkg.dir("MultipleTesting")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
