site_name: MultipleTesting.jl

site_description: Statistical p-value adjustment and estimation of the proportion of true null hypotheses

theme: readthedocs

repo_url: https://github.com/julian-gehring/MultipleTesting.jl

pages:
- Home: 'index.md'
- API: 'api.md'
- Notebooks:
  - 'Estimating Ï€0': 'notebooks/pi0-estimation.md'
- News: 'NEWS.md'
- About:
  - 'License': 'LICENSE.md'

docs_dir: doc

site_favicon: null

markdown_extensions: [codehilite, def_list, nl2br]
